import math


def fibonacci_series_math(n):
    series=[]
    # Golden ratio (φ), approximately 1.618...
    a = (1 + math.sqrt(5)) / 2  

    # Conjugate of the golden ratio (1 - φ), approximately -0.618...
    b = (1 - math.sqrt(5)) / 2  

    # Apply Binet's formula to compute the n-th Fibonacci number:
    # F(n) = (φ^n - (1 - φ)^n) / √5
    # Because of floating-point precision issues, we use round() 
    # to get the nearest integer as the final Fibonacci number.
    series=[round((math.pow(a, i) - math.pow(b, i)) / math.sqrt(5)) for  i  in range(0,n+1)]
    return  series;

# Compute n! (n factorial) using the built-in math.factorial function
def finonacci_factorial(n):
    # Delegate the computation to math.factorial, which efficiently computes n!
    return math.factorial(n)


#Generate series

def finonacci_series(n):
    # Initialize the list that will store the Fibonacci series
    series = []

    # Handle the case n == 0: only F(0) = 0
    series.append(0)
    if n == 0:
        return series
    # Handle the case n >= 1: append F(1) = 1
    series.append(1)
    if n == 1:
        return series
    
    # For n >= 2, iteratively compute each next Fibonacci number
    # using: F(k) = F(k-1) + F(k-2)
    for i in range (2,n+1):
       series.append(series[i-1]+series[i-2])
    return series

# Compute n! (n factorial) using iterative multiplication
def finonacci_mutiply(n):
   # Initialize the accumulator for the product (will store n!)
    total = 1

    # Multiply all integers from 1 up to n (inclusive)
    for i in range(1, n + 1):
        total *= i

    # Return the final product, which is n! (n factorial)
    return total


def factorial_recursion(n):
    """
    Compute the factorial of n recursively.
    
    Args:
        n (int): Non-negative integer

    Returns:
        int: n! (factorial of n)
    """
    # Base case: factorial of 0 is 1
    if n == 0:
        return 1
    
    # Recursive case: n! = n * (n-1)!
    return n * factorial_recursion(n-1)


# Main function for user interaction
def main():
    while True:
        try:
            input_variable = int(input('Please input a positive number: '))
            if input_variable < 0:
                print(f"This is a negative number")
                break

            print(f'The n! using iterative multiplication is {finonacci_mutiply(input_variable)}') 
             # Print all Fibonacci numbers generated by the dynamic approach
            print('Fibonacci series is ',end="")
            print('{', end='')
            print( *finonacci_series(input_variable), sep=', ',end='')
            print('}')

            
           

            print(f'The n! using math is {finonacci_factorial(input_variable)}') 
    
            # Print all Fibonacci numbers generated by the dynamic approach
            print('Fibonacci series through math is ',end="")
            print('{', end='')
            print( *fibonacci_series_math(input_variable), sep=', ',end='')
            print('}')

            print(f'The n! using recursion is {factorial_recursion(input_variable)}') 
            
        except ValueError:
            print("WARNING: This is not an integer! Please input again", end="")


if __name__ == "__main__":
    # Call main function to start Fibonacci program
    main()
